# Generated by Django 2.2.10 on 2020-07-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tour_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=50)),
            ],
        ),
    ]
