# Generated by Django 2.2.10 on 2020-07-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travelholic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('posted_date', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('crawled_date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TravelHolic',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tourtype',
            options={'managed': False},
        ),
    ]
